apiVersion: apps/v1
kind: Deployment
metadata:
  name: juntos-colaborar-function-prod
  labels:
    app: juntos-colaborar-function
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: juntos-colaborar-function
      environment: production
  template:
    metadata:
      labels:
        app: juntos-colaborar-function
        environment: production
    spec:
      containers:
      - name: juntos-colaborar-function
        image: juntos-colaborar-function:latest
        ports:
        - containerPort: 80
        env:
        - name: FUNCTIONS_WORKER_RUNTIME
          value: "dotnet-isolated"
        - name: RabbitMQConnectionString
          valueFrom:
            secretKeyRef:
              name: rabbitmq-connection
              key: connection-string
        - name: AzureWebJobsDisableHomepage
          value: "true"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: juntos-colaborar-service-prod
  labels:
    environment: production
spec:
  selector:
    app: juntos-colaborar-function
    environment: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-connection
type: Opaque
stringData:
  connection-string: "amqp://user:password@rabbitmq-prod.example.com:5672"